// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnlRUdxa7xTqapJEiUq5s21a84qYl--_M',
    appId: '1:806610414222:web:9cab507d3d7eb16b9077df',
    messagingSenderId: '806610414222',
    projectId: 'gov-citizen-app-691b1',
    authDomain: 'gov-citizen-app-691b1.firebaseapp.com',
    databaseURL: 'https://gov-citizen-app-691b1-default-rtdb.firebaseio.com',
    storageBucket: 'gov-citizen-app-691b1.firebasestorage.app',
    measurementId: 'G-0CJBQ5ZTKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM1KRVRJRE3sHq1jpgFYIyvJDVlG3M8hE',
    appId: '1:806610414222:android:f7e724b96dacc4949077df',
    messagingSenderId: '806610414222',
    projectId: 'gov-citizen-app-691b1',
    databaseURL: 'https://gov-citizen-app-691b1-default-rtdb.firebaseio.com',
    storageBucket: 'gov-citizen-app-691b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpBfEyUDtDgLVCksNktQoIzudVButFLkA',
    appId: '1:806610414222:ios:69fe13b9f179a9ee9077df',
    messagingSenderId: '806610414222',
    projectId: 'gov-citizen-app-691b1',
    databaseURL: 'https://gov-citizen-app-691b1-default-rtdb.firebaseio.com',
    storageBucket: 'gov-citizen-app-691b1.firebasestorage.app',
    iosBundleId: 'com.example.govCitizenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpBfEyUDtDgLVCksNktQoIzudVButFLkA',
    appId: '1:806610414222:ios:69fe13b9f179a9ee9077df',
    messagingSenderId: '806610414222',
    projectId: 'gov-citizen-app-691b1',
    databaseURL: 'https://gov-citizen-app-691b1-default-rtdb.firebaseio.com',
    storageBucket: 'gov-citizen-app-691b1.firebasestorage.app',
    iosBundleId: 'com.example.govCitizenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnlRUdxa7xTqapJEiUq5s21a84qYl--_M',
    appId: '1:806610414222:web:7102e0ed2e6cff439077df',
    messagingSenderId: '806610414222',
    projectId: 'gov-citizen-app-691b1',
    authDomain: 'gov-citizen-app-691b1.firebaseapp.com',
    databaseURL: 'https://gov-citizen-app-691b1-default-rtdb.firebaseio.com',
    storageBucket: 'gov-citizen-app-691b1.firebasestorage.app',
    measurementId: 'G-8H5C13DC62',
  );
}
